name: Deploy to New Aliyun Account

on:
  push:
    branches: [ "main" ]  # Changed to main to avoid conflicts with master
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  FRONTEND_IMAGE: bunbunspace/websiterepo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to New Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NEW_ALIYUN_USERNAME }}
          password: ${{ secrets.NEW_ALIYUN_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to new server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NEW_SSH_HOST }}
          username: ${{ secrets.NEW_SSH_USERNAME }}
          password: ${{ secrets.NEW_SSH_KEY }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
            docker stop new-static-portal || true
            docker rm new-static-portal || true
            docker run -d --name new-static-portal -p 8096:80 ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
